services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mudar123"
      MYSQL_DATABASE: "unicesumar"
    ports:
      - "3307:3306"
  
  adminer:
    image: adminer
    ports:
      - 8081:8080
